
  create table "public"."faculties" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."faculties" enable row level security;


  create table "public"."majors" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "faculty_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."majors" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null default auth.uid(),
    "role" text not null default 'student'::text,
    "created_at" timestamp with time zone not null default now(),
    "full_name" text not null
      );


alter table "public"."profiles" enable row level security;


  create table "public"."student_details" (
    "id" uuid not null,
    "student_code" text not null,
    "year_level" smallint not null,
    "created_at" timestamp with time zone not null default now(),
    "advisor_id" uuid not null,
    "major_id" bigint not null
      );


alter table "public"."student_details" enable row level security;


  create table "public"."students_test" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "nickname" text,
    "major" text,
    "created_at" timestamp with time zone not null default now()
      );



  create table "public"."teacher_details" (
    "id" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "major_id" bigint not null
      );


alter table "public"."teacher_details" enable row level security;

CREATE UNIQUE INDEX faculties_pkey ON public.faculties USING btree (id);

CREATE UNIQUE INDEX majors_pkey ON public.majors USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX student_details_pkey ON public.student_details USING btree (id);

CREATE UNIQUE INDEX student_details_student_code_key ON public.student_details USING btree (student_code);

CREATE UNIQUE INDEX students_test_pkey ON public.students_test USING btree (id);

CREATE UNIQUE INDEX teacher_details_pkey ON public.teacher_details USING btree (id);

alter table "public"."faculties" add constraint "faculties_pkey" PRIMARY KEY using index "faculties_pkey";

alter table "public"."majors" add constraint "majors_pkey" PRIMARY KEY using index "majors_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."student_details" add constraint "student_details_pkey" PRIMARY KEY using index "student_details_pkey";

alter table "public"."students_test" add constraint "students_test_pkey" PRIMARY KEY using index "students_test_pkey";

alter table "public"."teacher_details" add constraint "teacher_details_pkey" PRIMARY KEY using index "teacher_details_pkey";

alter table "public"."majors" add constraint "majors_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculties(id) ON DELETE CASCADE not valid;

alter table "public"."majors" validate constraint "majors_faculty_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."student_details" add constraint "student_details_advisor_id_fkey" FOREIGN KEY (advisor_id) REFERENCES public.teacher_details(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."student_details" validate constraint "student_details_advisor_id_fkey";

alter table "public"."student_details" add constraint "student_details_id_fkey" FOREIGN KEY (id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."student_details" validate constraint "student_details_id_fkey";

alter table "public"."student_details" add constraint "student_details_major_id_fkey" FOREIGN KEY (major_id) REFERENCES public.majors(id) ON DELETE SET NULL not valid;

alter table "public"."student_details" validate constraint "student_details_major_id_fkey";

alter table "public"."student_details" add constraint "student_details_student_code_key" UNIQUE using index "student_details_student_code_key";

alter table "public"."teacher_details" add constraint "teacher_details_id_fkey" FOREIGN KEY (id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."teacher_details" validate constraint "teacher_details_id_fkey";

alter table "public"."teacher_details" add constraint "teacher_details_major_id_fkey" FOREIGN KEY (major_id) REFERENCES public.majors(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."teacher_details" validate constraint "teacher_details_major_id_fkey";

grant delete on table "public"."faculties" to "anon";

grant insert on table "public"."faculties" to "anon";

grant references on table "public"."faculties" to "anon";

grant select on table "public"."faculties" to "anon";

grant trigger on table "public"."faculties" to "anon";

grant truncate on table "public"."faculties" to "anon";

grant update on table "public"."faculties" to "anon";

grant delete on table "public"."faculties" to "authenticated";

grant insert on table "public"."faculties" to "authenticated";

grant references on table "public"."faculties" to "authenticated";

grant select on table "public"."faculties" to "authenticated";

grant trigger on table "public"."faculties" to "authenticated";

grant truncate on table "public"."faculties" to "authenticated";

grant update on table "public"."faculties" to "authenticated";

grant delete on table "public"."faculties" to "service_role";

grant insert on table "public"."faculties" to "service_role";

grant references on table "public"."faculties" to "service_role";

grant select on table "public"."faculties" to "service_role";

grant trigger on table "public"."faculties" to "service_role";

grant truncate on table "public"."faculties" to "service_role";

grant update on table "public"."faculties" to "service_role";

grant delete on table "public"."majors" to "anon";

grant insert on table "public"."majors" to "anon";

grant references on table "public"."majors" to "anon";

grant select on table "public"."majors" to "anon";

grant trigger on table "public"."majors" to "anon";

grant truncate on table "public"."majors" to "anon";

grant update on table "public"."majors" to "anon";

grant delete on table "public"."majors" to "authenticated";

grant insert on table "public"."majors" to "authenticated";

grant references on table "public"."majors" to "authenticated";

grant select on table "public"."majors" to "authenticated";

grant trigger on table "public"."majors" to "authenticated";

grant truncate on table "public"."majors" to "authenticated";

grant update on table "public"."majors" to "authenticated";

grant delete on table "public"."majors" to "service_role";

grant insert on table "public"."majors" to "service_role";

grant references on table "public"."majors" to "service_role";

grant select on table "public"."majors" to "service_role";

grant trigger on table "public"."majors" to "service_role";

grant truncate on table "public"."majors" to "service_role";

grant update on table "public"."majors" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."student_details" to "anon";

grant insert on table "public"."student_details" to "anon";

grant references on table "public"."student_details" to "anon";

grant select on table "public"."student_details" to "anon";

grant trigger on table "public"."student_details" to "anon";

grant truncate on table "public"."student_details" to "anon";

grant update on table "public"."student_details" to "anon";

grant delete on table "public"."student_details" to "authenticated";

grant insert on table "public"."student_details" to "authenticated";

grant references on table "public"."student_details" to "authenticated";

grant select on table "public"."student_details" to "authenticated";

grant trigger on table "public"."student_details" to "authenticated";

grant truncate on table "public"."student_details" to "authenticated";

grant update on table "public"."student_details" to "authenticated";

grant delete on table "public"."student_details" to "service_role";

grant insert on table "public"."student_details" to "service_role";

grant references on table "public"."student_details" to "service_role";

grant select on table "public"."student_details" to "service_role";

grant trigger on table "public"."student_details" to "service_role";

grant truncate on table "public"."student_details" to "service_role";

grant update on table "public"."student_details" to "service_role";

grant delete on table "public"."students_test" to "anon";

grant insert on table "public"."students_test" to "anon";

grant references on table "public"."students_test" to "anon";

grant select on table "public"."students_test" to "anon";

grant trigger on table "public"."students_test" to "anon";

grant truncate on table "public"."students_test" to "anon";

grant update on table "public"."students_test" to "anon";

grant delete on table "public"."students_test" to "authenticated";

grant insert on table "public"."students_test" to "authenticated";

grant references on table "public"."students_test" to "authenticated";

grant select on table "public"."students_test" to "authenticated";

grant trigger on table "public"."students_test" to "authenticated";

grant truncate on table "public"."students_test" to "authenticated";

grant update on table "public"."students_test" to "authenticated";

grant delete on table "public"."students_test" to "service_role";

grant insert on table "public"."students_test" to "service_role";

grant references on table "public"."students_test" to "service_role";

grant select on table "public"."students_test" to "service_role";

grant trigger on table "public"."students_test" to "service_role";

grant truncate on table "public"."students_test" to "service_role";

grant update on table "public"."students_test" to "service_role";

grant delete on table "public"."teacher_details" to "anon";

grant insert on table "public"."teacher_details" to "anon";

grant references on table "public"."teacher_details" to "anon";

grant select on table "public"."teacher_details" to "anon";

grant trigger on table "public"."teacher_details" to "anon";

grant truncate on table "public"."teacher_details" to "anon";

grant update on table "public"."teacher_details" to "anon";

grant delete on table "public"."teacher_details" to "authenticated";

grant insert on table "public"."teacher_details" to "authenticated";

grant references on table "public"."teacher_details" to "authenticated";

grant select on table "public"."teacher_details" to "authenticated";

grant trigger on table "public"."teacher_details" to "authenticated";

grant truncate on table "public"."teacher_details" to "authenticated";

grant update on table "public"."teacher_details" to "authenticated";

grant delete on table "public"."teacher_details" to "service_role";

grant insert on table "public"."teacher_details" to "service_role";

grant references on table "public"."teacher_details" to "service_role";

grant select on table "public"."teacher_details" to "service_role";

grant trigger on table "public"."teacher_details" to "service_role";

grant truncate on table "public"."teacher_details" to "service_role";

grant update on table "public"."teacher_details" to "service_role";


  create policy "Users can view their own profile"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can view their own student details"
  on "public"."student_details"
  as permissive
  for select
  to public
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can view their own teacher details"
  on "public"."teacher_details"
  as permissive
  for select
  to public
using ((( SELECT auth.uid() AS uid) = id));




